version: "3.7"
services:
  db:
    image: postgres:latest
    container_name: PSQLprzedszkoles
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      przedszkole:
        aliases:
          - przedszkole
    ports:
      - "5432:5432"
    expose:
      - "5432"

  web:
    build: .
    container_name: DJANGOprzedszkoles
    depends_on:
      - db
    restart: always
    volumes:
      - ./static:/static
      - ./media:/media
    entrypoint: ./docker-entrypoint.sh
    command: gunicorn przedszkole.wsgi:application -b 0.0.0.0:8001
    networks:
      - przedszkole
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./static:/static
      - ./media:/media
    networks:
      - przedszkole



networks:
  przedszkole:
    external: true
    driver: bridge

volumes:
  pgdata:
  postgres: