# Generated by Django 2.2.3 on 2019-07-25 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elementy',
            fields=[
                ('ID', models.AutoField(default=1, editable=False, primary_key=True, serialize=False)),
                ('nazwa_elementu', models.CharField(max_length=255, verbose_name='Element statyczny strony głównej')),
                ('nazwa_uzytkownika_elementu', models.CharField(max_length=255, verbose_name='Uproszczona nazwa uzytkownika')),
            ],
        ),
        migrations.CreateModel(
            name='NrElementowGlownych',
            fields=[
                ('ID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('typ', models.CharField(max_length=255, verbose_name='Jaki rodzaj elementu')),
            ],
        ),
        migrations.CreateModel(
            name='Strona',
            fields=[
                ('ID', models.AutoField(default=1, editable=False, primary_key=True, serialize=False)),
                ('nazwa_podreczna', models.CharField(max_length=255, verbose_name='Nazwa dla listy stron')),
                ('tytul', models.CharField(max_length=255, verbose_name='Tytul strony')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data wydania')),
                ('tresc', models.TextField(default='')),
                ('odnosnik_do_galerii', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.DO_NOTHING, to='gallery.Album', verbose_name='Nazwa albumu')),
            ],
        ),
        migrations.CreateModel(
            name='PodElementy',
            fields=[
                ('ID_pod', models.AutoField(default=1, editable=False, primary_key=True, serialize=False)),
                ('tytul', models.CharField(max_length=255, verbose_name='Napis na elemencie')),
                ('zdjecie', models.ImageField(upload_to='images/', verbose_name='Wybor zdjecia (Tylko dla slidera)')),
                ('link_do_strony', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='website.Strona')),
                ('powiazanie_z_elementem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='website.Elementy')),
            ],
        ),
        migrations.AddField(
            model_name='elementy',
            name='flaga_elementu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='website.NrElementowGlownych'),
        ),
        migrations.CreateModel(
            name='Aktualnosci',
            fields=[
                ('ID', models.AutoField(default=1, editable=False, primary_key=True, serialize=False)),
                ('tytul', models.CharField(max_length=255, verbose_name='Tytul strony')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data wydania')),
                ('tresc', models.TextField(default='')),
                ('important', models.BooleanField(default=False)),
                ('odnosnik_do_galerii', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gallery.Album', verbose_name='Nazwa albumu')),
            ],
        ),
    ]
