# Generated by Django 2.2.4 on 2019-08-12 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Elementy',
            fields=[
                ('ID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nazwa_elementu', models.CharField(editable=False, max_length=255, verbose_name='Element statyczny strony głównej !nie zmieniać!')),
                ('nazwa_uzytkownika_elementu', models.CharField(blank=True, max_length=255, verbose_name='Napis na elemencie')),
                ('kategoria', models.CharField(max_length=255, verbose_name='Kategoria elementu')),
            ],
            options={
                'verbose_name_plural': 'Elementy na stronie www',
            },
        ),
        migrations.CreateModel(
            name='Strona',
            fields=[
                ('ID', models.AutoField(default=1, editable=False, primary_key=True, serialize=False)),
                ('nazwa_podreczna', models.CharField(max_length=255, verbose_name='Nazwa dla listy stron')),
                ('tytul', models.CharField(max_length=255, verbose_name='Tytul strony')),
                ('data', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data wydania')),
                ('tresc', models.TextField(default='')),
                ('statyczna', models.BooleanField(blank=True, default=False, verbose_name='Jeżeli strona jest statyczna')),
                ('link_statyczny', models.CharField(blank=True, default='', max_length=255, verbose_name='Link do strony statycznej')),
                ('odnosnik_do_galerii', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gallery.Album', verbose_name='Nazwa albumu')),
            ],
            options={
                'verbose_name_plural': 'Podstrony www',
            },
        ),
        migrations.CreateModel(
            name='PodElementy',
            fields=[
                ('ID_pod', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('tytul', models.CharField(max_length=255, verbose_name='Napis na elemencie')),
                ('zdjecie', models.ImageField(blank=True, upload_to='images/slider/', verbose_name='Wybor zdjecia (Tylko dla slidera)')),
                ('order', models.IntegerField(default=0, verbose_name='Kolejność')),
                ('link_do_strony', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='website.Strona')),
                ('powiazanie_z_elementem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='website.Elementy', verbose_name='Z jakim elementem wspolpracuje')),
            ],
            options={
                'verbose_name_plural': 'Elementy użytkownika',
            },
        ),
        migrations.CreateModel(
            name='GrupyPrzedszkolne',
            fields=[
                ('nazwa_grupy', models.CharField(max_length=255, verbose_name='Nazwa Grupy')),
                ('skrot', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Skrót nazwy')),
                ('rodzice', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Grupy w przedszkolu',
            },
        ),
        migrations.CreateModel(
            name='Aktualnosci',
            fields=[
                ('ID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('tytul', models.CharField(max_length=255, verbose_name='Tytul')),
                ('data', models.DateTimeField(null=True, verbose_name='Data wydania')),
                ('tresc', models.TextField(default='')),
                ('important', models.BooleanField(default=False, verbose_name='Komunikat')),
                ('zdjecie', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='images/aktualnosci/')),
                ('visible', models.BooleanField(default=True, verbose_name='Widoczne')),
                ('odnosnik_do_galerii', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gallery.Album', verbose_name='Nazwa albumu')),
            ],
            options={
                'verbose_name_plural': 'Posty na stronie głównej',
            },
        ),
    ]
