# Generated by Django 2.2.3 on 2019-07-25 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktualnosci',
            name='zdjecie',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Zdjecie na podglad'),
        ),
    ]
