# Generated by Django 2.2.3 on 2019-07-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_aktualnosci_zdjecie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aktualnosci',
            options={'verbose_name_plural': 'Posty na stronie głównej'},
        ),
        migrations.AlterModelOptions(
            name='elementy',
            options={'verbose_name_plural': 'Elementy na stronie www'},
        ),
        migrations.AlterModelOptions(
            name='nrelementowglownych',
            options={'verbose_name_plural': 'Typy elementów na stronie www'},
        ),
        migrations.AlterModelOptions(
            name='podelementy',
            options={'verbose_name_plural': 'Elementy użytkownika'},
        ),
        migrations.AlterModelOptions(
            name='strona',
            options={'verbose_name_plural': 'Podstrony www'},
        ),
        migrations.AddField(
            model_name='aktualnosci',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='aktualnosci',
            name='zdjecie',
            field=models.ImageField(blank=True, upload_to='images/aktualnosci/', verbose_name='Zdjecie na podglad'),
        ),
        migrations.AlterField(
            model_name='podelementy',
            name='zdjecie',
            field=models.ImageField(upload_to='images/slider/', verbose_name='Wybor zdjecia (Tylko dla slidera)'),
        ),
    ]
