# Generated by Django 2.2.4 on 2019-08-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
        ('website', '0002_aktualnosci_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupyprzedszkolne',
            name='rodzice',
        ),
        migrations.AddField(
            model_name='aktualnosci',
            name='do_kogo',
            field=models.ManyToManyField(blank=True, default=0, to='website.GrupyPrzedszkolne', verbose_name='Gdzie ma być wyswietlana aktualność (domyslnie na głównej)'),
        ),
        migrations.AddField(
            model_name='grupyprzedszkolne',
            name='albumy_zdjeciowe',
            field=models.ManyToManyField(blank=True, to='gallery.Album', verbose_name='Nazwy albumów powiazane z grupa przedszkolna'),
        ),
    ]
