# Generated by Django 2.2.3 on 2019-07-26 10:35

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20190726_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktualnosci',
            name='data',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data wydania'),
        ),
        migrations.AlterField(
            model_name='aktualnosci',
            name='important',
            field=models.BooleanField(default=False, verbose_name='Komunikat'),
        ),
        migrations.AlterField(
            model_name='aktualnosci',
            name='tytul',
            field=models.CharField(max_length=255, verbose_name='Tytul'),
        ),
        migrations.AlterField(
            model_name='aktualnosci',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Widoczne'),
        ),
        migrations.AlterField(
            model_name='aktualnosci',
            name='zdjecie',
            field=imagekit.models.fields.ProcessedImageField(upload_to='images/aktualnosci/'),
        ),
    ]
