# Generated by Django 2.2.3 on 2019-07-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20190726_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strona',
            name='data',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data wydania'),
        ),
    ]
