# Generated by Django 2.2.4 on 2019-08-15 22:48

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20190816_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupyprzedszkolne',
            name='zdjecie_grupy',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='images/grupy/'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='zdjecie',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='images/slidergorny/'),
        ),
    ]
