# Generated by Django 2.2.4 on 2019-08-20 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20190816_0048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aktualnosci',
            options={'verbose_name_plural': 'Wpisy aktualności'},
        ),
    ]
