# Generated by Django 2.2.3 on 2019-07-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20190726_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktualnosci',
            name='data',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data wydania'),
        ),
        migrations.AlterField(
            model_name='strona',
            name='data',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data wydania'),
        ),
    ]
