# Generated by Django 2.2.4 on 2019-08-25 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20190820_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktualnosci',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.Event', verbose_name='Wydarzenie w kalendarzu'),
        ),
    ]
