# Generated by Django 2.2.3 on 2019-07-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20190726_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupyPrzedszkolne',
            fields=[
                ('nazwa_grupy', models.CharField(max_length=255, verbose_name='Nazwa Grupy')),
                ('skrot', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Skrót nazwy')),
            ],
            options={
                'verbose_name_plural': 'Grupy w przedszkolu',
            },
        ),
        migrations.AlterField(
            model_name='aktualnosci',
            name='data',
            field=models.DateTimeField(null=True, verbose_name='Data wydania'),
        ),
    ]
