# Generated by Django 2.2.4 on 2019-08-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20190825_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strona',
            name='ID',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
