# Generated by Django 2.2.3 on 2019-07-26 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0008_auto_20190726_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktualnosci',
            name='zdjecie',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='images/aktualnosci/'),
        ),
        migrations.AlterField(
            model_name='podelementy',
            name='zdjecie',
            field=models.ImageField(blank=True, upload_to='images/slider/', verbose_name='Wybor zdjecia (Tylko dla slidera)'),
        ),
        migrations.CreateModel(
            name='RodziceDoGrupy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDGrupy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='website.GrupyPrzedszkolne')),
                ('IDRodzica', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Przypisanie rodziców do grupy',
            },
        ),
    ]
