# Generated by Django 2.2.3 on 2019-07-26 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_grupyprzedszkolne_rodzice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RodziceDoGrupy',
        ),
    ]
