# Generated by Django 2.2.3 on 2019-07-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20190726_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementy',
            name='kategoria',
            field=models.CharField(default=0, max_length=255, verbose_name='Kategoria elementu'),
            preserve_default=False,
        ),
    ]
