# Generated by Django 2.2.3 on 2019-07-26 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_elementy_kategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementy',
            name='nazwa_uzytkownika_elementu',
            field=models.CharField(blank=True, max_length=255, verbose_name='Napis na elemencie'),
        ),
        migrations.AlterField(
            model_name='strona',
            name='odnosnik_do_galerii',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gallery.Album', verbose_name='Nazwa albumu'),
        ),
    ]
