# Generated by Django 2.2.3 on 2019-08-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20190726_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='podelementy',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Kolejność'),
        ),
        migrations.AlterField(
            model_name='elementy',
            name='nazwa_elementu',
            field=models.CharField(editable=False, max_length=255, verbose_name='Element statyczny strony głównej !nie zmieniać!'),
        ),
    ]
