# Generated by Django 2.2.3 on 2019-08-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20190802_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podelementy',
            name='ID_pod',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
