# Generated by Django 2.2.3 on 2019-08-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20190803_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='strona',
            name='link_statyczny',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Link do strony statycznej'),
        ),
        migrations.AddField(
            model_name='strona',
            name='statyczna',
            field=models.BooleanField(blank=True, default=False, verbose_name='Jeżeli strona jest statyczna'),
        ),
    ]
