# Generated by Django 2.2.3 on 2019-08-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_auto_20190803_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktualnosci',
            name='ID',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
