# Generated by Django 2.2.3 on 2019-08-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_auto_20190803_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podelementy',
            name='tytul',
            field=models.CharField(max_length=255, verbose_name='Napis na elemencie'),
        ),
    ]
