# Generated by Django 2.2.4 on 2019-08-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_event_calendar_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, editable=False, verbose_name='description'),
        ),
    ]
